import Data.Bits
import Data.Word
(.<.) = shiftL
(.>.) = shiftR
v_a::Word16

v_bo = v_bn .>. 2
v_ly = v_lf .>. 1
v_fq = v_fo .>. 3
v_cq = v_cj .|. v_cp
v_ga = v_fo .|. v_fz
v_u = v_t .|. v_s
v_a = v_lx
v_ay = complement v_ax
v_hf = v_he .>. 2
v_lr = v_lf .|. v_lq
v_lu = v_lr .&. v_lt
v_ek = v_dy .|. v_ej
v_cy = 1 .&. v_cx
v_hv = v_hb .<. 1
v_bi = 1 .&. v_bh
v_ik = v_ih .&. v_ij
v_t = v_c .<. 1
v_ed = v_ea .&. v_eb
v_ko = v_km .|. v_kn
v_bx = complement v_bw
v_cu = v_ci .|. v_ct
v_q = complement v_p
v_lx = v_lw .|. v_lv
v_lp = complement v_lo
v_fw = v_fp .|. v_fv
v_r = v_o .&. v_q
v_dk = v_dh .&. v_dj
v_bj = v_ap .<. 1
v_ce = v_bk .<. 1
v_ij = complement v_ii
v_gj = v_gh .|. v_gi
v_ld = v_kk .>. 1
v_lw = v_lc .<. 1
v_lc = v_lb .|. v_la
v_an = 1 .&. v_am
v_gq = v_gn .&. v_gp
v_lh = v_lf .>. 3
v_g = v_e .|. v_f
v_lo = v_lg .&. v_lm
v_db = v_ci .>. 1
v_cz = v_cf .<. 1
v_cg = v_bn .>. 1
v_fg = v_et .&. v_fe
v_iu = v_is .|. v_it
v_kz = v_kw .&. v_ky
v_cn = v_ck .&. v_cl
v_bk = v_bj .|. v_bi
v_hc = v_gj .>. 1
v_jh = v_iu .&. v_jf
v_bt = complement v_bs
v_kw = v_kk .|. v_kv
v_kv = v_ks .&. v_ku
v_il = v_hz .|. v_ik
v_v = v_b .>. 1
v_jn = v_iu .>. 1
v_fr = v_fo .>. 5
v_bh = v_be .&. v_bg
v_gd = v_ga .&. v_gc
v_hm = v_hf .|. v_hl
v_lf = v_ld .|. v_le
v_av = v_as .>. 5
v_fo = v_fm .|. v_fn
v_hp = v_hm .&. v_ho
v_ln = v_lg .|. v_lm
v_ky = complement v_kx
v_km = v_kk .>. 3
v_en = v_ek .&. v_em
v_fu = complement v_ft
v_ji = complement v_jh
v_jp = v_jn .|. v_jo
v_gw = v_gj .&. v_gu
v_l = v_d .&. v_j
v_fm = v_et .>. 1
v_jx = v_jq .|. v_jw
v_eq = v_ep .|. v_eo
v_lz = v_lv .<. 15
v_ez = complement v_ey
v_jq = v_jp .>. 2
v_ej = v_eg .&. v_ei
v_dn = complement v_dm
v_kc = v_jp .&. v_ka
v_bf = v_as .&. v_bd
v_fl = v_fk .|. v_fj
v_dy = v_dw .|. v_dx
v_lm = v_lj .&. v_ll
v_ef = v_ec .&. v_ee
v_ft = v_fq .&. v_fr
v_kq = complement v_kp
v_kk = v_ki .|. v_kj
v_da = v_cz .|. v_cy
v_au = v_as .>. 3
v_ar = v_an .<. 15
v_fn = v_fj .<. 15
v_fj = 1 .&. v_fi
v_hx = v_he .>. 1
v_lg = v_lf .>. 2
v_kj = v_kf .<. 15
v_eh = v_dz .&. v_ef
v_id = v_ib .|. v_ic
v_li = v_lf .>. 5
v_br = v_bp .|. v_bq
v_gt = complement v_gs
v_gh = v_fo .>. 1
v_cc = v_bz .&. v_cb
v_ec = v_ea .|. v_eb
v_ls = v_lf .&. v_lq
v_m = complement v_l
v_ib = v_hz .>. 3
v_dj = complement v_di
v_ll = complement v_lk
v_jr = v_jp .>. 3
v_js = v_jp .>. 5
v_bg = complement v_bf
v_w = v_s .<. 15
v_fk = v_eq .<. 1
v_jm = v_jl .|. v_jk
v_im = v_hz .&. v_ik
v_eg = v_dz .|. v_ef
v_gz = 1 .&. v_gy
v_le = v_la .<. 15
v_bu = v_br .&. v_bt
v_co = complement v_cn
v_x = v_v .|. v_w
v_k = v_d .|. v_j
v_ge = 1 .&. v_gd
v_ih = v_ia .|. v_ig
v_gp = complement v_go
v_ee = complement v_ed
v_jy = v_jq .&. v_jw
v_ff = v_et .|. v_fe
v_az = v_aw .&. v_ay
v_fi = v_ff .&. v_fh
v_jl = v_ir .<. 1
v_ha = v_gg .<. 1
v_y = v_x .>. 2
v_dd = v_db .|. v_dc
v_bn = v_bl .|. v_bm
v_ie = v_ib .&. v_ic
v_z = v_x .>. 3
v_lk = v_lh .&. v_li
v_cf = v_ce .|. v_cd
v_bc = complement v_bb
v_hl = v_hi .&. v_hk
v_gc = complement v_gb
v_s = 1 .&. v_r
v_fz = v_fw .&. v_fy
v_fe = v_fb .&. v_fd
v_eo = 1 .&. v_en
v_ab = v_z .|. v_aa
v_bm = v_bi .<. 15
v_hi = v_hg .|. v_hh
v_lb = v_kh .<. 1
v_ci = v_cg .|. v_ch
v_la = 1 .&. v_kz
v_gg = v_gf .|. v_ge
v_gk = v_gj .>. 2
v_de = v_dd .>. 2
v_lt = complement v_ls
v_lj = v_lh .|. v_li
v_jt = v_jr .|. v_js
v_ax = v_au .&. v_av
v_c = 0
v_hr = v_he .&. v_hp
v_ig = v_id .&. v_if
v_ew = v_et .>. 5
v_bs = v_bp .&. v_bq
v_h = v_e .&. v_f
v_ma = v_ly .|. v_lz
v_lv = 1 .&. v_lu
v_je = complement v_jd
v_hb = v_ha .|. v_gz
v_er = v_dy .>. 1
v_iv = v_iu .>. 2
v_hs = complement v_hr
v_bl = v_as .>. 1
v_kl = v_kk .>. 2
v_p = v_b .&. v_n
v_lq = v_ln .&. v_lp
v_cr = v_cj .&. v_cp
v_do = v_dl .&. v_dn
v_cj = v_ci .>. 2
v_be = v_as .|. v_bd
v_gi = v_ge .<. 15
v_ic = v_hz .>. 5
v_ep = v_dv .<. 1
v_ks = v_kl .|. v_kr
v_gv = v_gj .|. v_gu
v_hh = v_he .>. 5
v_fh = complement v_fg
v_hj = v_hg .&. v_hh
v_o = v_b .|. v_n
v_jo = v_jk .<. 15
v_hd = v_gz .<. 15
v_dc = v_cy .<. 15
v_kn = v_kk .>. 5
v_ck = v_ci .>. 3
v_ba = v_at .|. v_az
v_iw = v_iu .>. 3
v_kr = v_ko .&. v_kq
v_ei = complement v_eh
v_as = v_aq .|. v_ar
v_jb = v_iy .&. v_ja
v_df = v_dd .>. 3
v_bp = v_bn .>. 3
v_cd = 1 .&. v_cc
v_bb = v_at .&. v_az
v_aj = v_x .|. v_ai
v_kx = v_kk .&. v_kv
v_ap = v_ao .|. v_an
v_ea = v_dy .>. 3
v_aq = v_x .>. 1
v_fc = v_eu .&. v_fa
v_kt = v_kl .&. v_kr
v_ii = v_ia .&. v_ig
v_di = v_df .&. v_dg
v_fy = complement v_fx
v_n = v_k .&. v_m
v_bq = v_bn .>. 5
v_kp = v_km .&. v_kn
v_dx = v_dt .<. 15
v_ia = v_hz .>. 2
v_am = v_aj .&. v_al
v_ch = v_cd .<. 15
v_he = v_hc .|. v_hd
v_hg = v_he .>. 3
v_bz = v_bn .|. v_by
v_ku = complement v_kt
v_ac = v_z .&. v_aa
v_al = complement v_ak
v_cx = v_cu .&. v_cw
v_if = complement v_ie
v_dz = v_dy .>. 2
v_it = v_ip .<. 15
v_dl = v_de .|. v_dk
v_aw = v_au .|. v_av
v_jj = v_jg .&. v_ji
v_cv = v_ci .&. v_ct
v_eb = v_dy .>. 5
v_hz = v_hx .|. v_hy
v_fb = v_eu .|. v_fa
v_gl = v_gj .>. 3
v_gb = v_fo .&. v_fz
v_jk = 1 .&. v_jj
v_kb = v_jp .|. v_ka
v_dm = v_de .&. v_dk
v_fa = v_ex .&. v_ez
v_dh = v_df .|. v_dg
v_jc = v_iv .|. v_jb
v_aa = v_x .>. 5
v_hk = complement v_hj
v_in = complement v_im
v_gf = v_fl .<. 1
v_hy = v_hu .<. 15
v_ir = v_iq .|. v_ip
v_ix = v_iu .>. 5
v_fd = complement v_fc
v_em = complement v_el
v_cm = v_ck .|. v_cl
v_ev = v_et .>. 3
v_iq = v_hw .<. 1
v_cl = v_ci .>. 5
v_jd = v_iv .&. v_jb
v_dg = v_dd .>. 5
v_at = v_as .>. 2
v_jz = complement v_jy
v_ai = v_af .&. v_ah
v_dt = 1 .&. v_ds
v_ka = v_jx .&. v_jz
v_du = v_da .<. 1
v_fv = v_fs .&. v_fu
v_ki = v_jp .>. 1
v_iz = v_iw .&. v_ix
v_iy = v_iw .|. v_ix
v_es = v_eo .<. 15
v_ey = v_ev .&. v_ew
v_bd = v_ba .&. v_bc
v_fx = v_fp .&. v_fv
v_jf = v_jc .&. v_je
v_eu = v_et .>. 2
v_kh = v_kg .|. v_kf
v_jg = v_iu .|. v_jf
v_et = v_er .|. v_es
v_fp = v_fo .>. 2
v_cb = complement v_ca
v_by = v_bv .&. v_bx
v_ao = v_u .<. 1
v_cp = v_cm .&. v_co
v_af = v_y .|. v_ae
v_ca = v_bn .&. v_by
v_kf = 1 .&. v_ke
v_jw = v_jt .&. v_jv
v_fs = v_fq .|. v_fr
v_el = v_dy .&. v_ej
v_kd = complement v_kc
v_ex = v_ev .|. v_ew
v_dp = v_dd .|. v_do
v_cw = complement v_cv
v_gu = v_gr .&. v_gt
v_dw = v_dd .>. 1
v_gx = complement v_gw
v_ja = complement v_iz
v_ip = 1 .&. v_io
v_ah = complement v_ag
v_f = v_b .>. 5
v_cs = complement v_cr
v_ke = v_kb .&. v_kd
v_ju = v_jr .&. v_js
v_ct = v_cq .&. v_cs
v_io = v_il .&. v_in
v_jv = complement v_ju
v_dv = v_du .|. v_dt
v_dq = v_dd .&. v_do
v_d = v_b .>. 2
v_kg = v_jm .<. 1
v_dr = complement v_dq
v_bv = v_bo .|. v_bu
v_gr = v_gk .|. v_gq
v_hq = v_he .|. v_hp
v_i = complement v_h
v_hn = v_hf .&. v_hl
v_gy = v_gv .&. v_gx
v_ak = v_x .&. v_ai
v_bw = v_bo .&. v_bu
v_ht = v_hq .&. v_hs
v_is = v_hz .>. 1
v_gm = v_gj .>. 5
v_j = v_g .&. v_i
v_gs = v_gk .&. v_gq
v_ds = v_dp .&. v_dr
v_e = v_b .>. 3
v_go = v_gl .&. v_gm
v_gn = v_gl .|. v_gm
v_ag = v_y .&. v_ae
v_hw = v_hv .|. v_hu
v_b = 1674
v_ae = v_ab .&. v_ad
v_ad = complement v_ac
v_hu = 1 .&. v_ht
v_ho = complement v_hn

main = print v_a

